repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
      - id: ruff # linter
        args: [--fix, --exit-non-zero-on-fix] # enable autofix lints
      - id: ruff-format # formater
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: python -m unittest discover
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
